# Generated by Django 4.0.4 on 2022-06-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_producto')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='nombre_producto')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='rut del usuario'),
        ),
    ]
