# Generated by Django 4.0.4 on 2022-06-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_alter_usuario_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de categoria')),
                ('nombre_categoria', models.CharField(max_length=50, verbose_name='nombre de la categoria')),
            ],
        ),
    ]
